os: Visual Studio 2017

clone_folder: c:/projects/units

branches:
  except:
    - gh-pages
    - documentation

platform:
  - x64

configuration:
  - Debug
  - Release

environment:
  matrix:
    - VS_GEN: Visual Studio 15 2017 Win64

build_script:
  - md build
  - cd build
  - cmake -Wno-dev -DUNITS_BUILD_TESTS=ON -G"%VS_GEN%" ..
  - cmake --build . --config %CONFIGURATION%

test_script:
  - cmd: ctest -VV -C %CONFIGURATION%

